version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql

  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./src:/src
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: god
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: "root"
      PMA_PASSWORD: "root"
    links:
      - mysql
    ports:
      - 8888:80
    volumes:
      - /sessions

